### POST Harvest (unAuthorized)
POST https://localhost:7214/api/Harvests
Content-Type: application/json

{
  "cropType": "Corn",
  "quantity": 500.10,
  "harvestDate": "2025-09-01"
}

### POST Harvest (Authorized)
POST https://localhost:7214/api/Harvests
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8J6kXnQBMyxPiGWCYMmdsYonBRnwWMT6ean-sxtC4jomYyeSLiTihvFYc_gyTEiezhobv-1GP7mIFugSC9Q22o2U71yMVqD9iRctvB6xKzqkWLh2r2KLbLAA5XSW6ctj5bU9wG1k22I48rTdquiN8-mNSqe6PvFCwKT1WYvaPJ0PrjLmtERUeT14pcZWvzqAZwsI-EP05Hf2ZuK-E7dO7fIFTCrzWuIVzpFxnQ4Q7yFUrz7I8o8GEZlxCLeTQk24xdV9dqdkSbCV4RdGlXdDMncjqE8AJue5hF6SbUDZ_lMYe_x_gPE-zdlRTJaD52vwQ_jQ98wy-dKOewnxDdFDnsseBCHTsdONJ_O3mPOQd-QtBzMzrKCv4V8LILhsN6-wAxJVKY6GoF3ppacg4zC7xdC25jt8gx7te5Gc-Klje1h3kbpkFNh9IBCTCkBmal3TnJKhncL2A562bfx8H7fNMIstxEmg3qbVaR2Wx4WZGAAsuiO7OfxD8Z6WR_fwZjf0tsg_NG8I_zXDRRQBNoRMsPHefdec4oWEG_0rDU43D0R0t7oCRE0feJmV-vWM3TbO4cznmtUBGjJlSMzIYMS1eYow0EgBOft7ofWCv_5-qW6AsOaGpuT04NvNoIq5LefONhYa0Hy2TlNaJ4HS6IfHuGh-bfD1Bf3pisckGQt-SrXC1K_6U35x25czKCBpg1mcPsZx3VQdeZRGmrV8hIG8eak4ML96VenO9wABgoddT7R_LEmyR28Ag6HB1rKuOBic-sQ2YCqF7PAWATzE63FOJaLATKCWP1NSMaM7Mhz7q_VnJsASViqM9HSxsMLW88916g

{
  "cropType": "Corn",
  "quantity": 500.10,
  "harvestDate": "2025-09-01"
}
